# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
 name: linux-server

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'mayureshmulye/devops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
